import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const testDir = dirname(fileURLToPath(import.meta.url));
const appDir = resolve(testDir, "..");

test("basic shell exposes create join ready leave and status targets", () => {
  const html = readFileSync(resolve(appDir, "index.html"), "utf8");

  assert.match(html, /id="create-room"/);
  assert.match(html, /id="transport-mode"/);
  assert.match(html, /id="transport-mode-status"/);
  assert.match(html, /value="real-server"/);
  assert.match(html, /id="join-code"/);
  assert.match(html, /id="join-room"/);
  assert.match(html, /id="restore-room"/);
  assert.match(html, /id="reconnect-live-sync"/);
  assert.match(html, /id="join-quick-match"/);
  assert.match(html, /id="leave-quick-match"/);
  assert.match(html, /id="quick-match-status"/);
  assert.match(html, /id="clear-room"/);
  assert.match(html, /id="room-status"/);
  assert.match(html, /id="phase-status"/);
  assert.match(html, /id="seat-status"/);
  assert.match(html, /id="turn-status"/);
  assert.match(html, /id="action-status"/);
  assert.match(html, /id="visual-phase"/);
  assert.match(html, /id="visual-seat"/);
  assert.match(html, /id="visual-action"/);
  assert.match(html, /id="visual-score-summary"/);
  assert.match(html, /id="visual-bid-bag-summary"/);
  assert.match(html, /id="visual-hand"/);
  assert.match(html, /id="visual-current-trick"/);
  assert.match(html, /id="visual-last-trick"/);
  assert.match(html, /id="table-opponent-area"/);
  assert.match(html, /id="table-score-area"/);
  assert.match(html, /id="table-center-trick-area"/);
  assert.match(html, /id="table-last-trick-area"/);
  assert.match(html, /id="table-player-hand-area"/);
  assert.match(html, /id="table-leave-room"/);
  assert.match(html, /id="table-record-history"/);
  assert.match(html, /id="table-start-next-hand"/);
  assert.match(html, /id="table-start-new-match"/);
  assert.match(html, /id="qa-check-list"/);
  assert.match(html, /id="qa-edge-list"/);
  assert.match(html, /id="beta-safety-check-list"/);
  assert.match(html, /id="manual-beta-flow-list"/);
  assert.match(html, /id="action-log-list"/);
  assert.match(html, /id="bid-status"/);
  assert.match(html, /id="bid-input"/);
  assert.match(html, /id="submit-bid"/);
  assert.match(html, /id="submit-nil"/);
  assert.match(html, /id="shell-error"/);
  assert.match(html, /id="manual-setup"/);
  assert.match(html, /id="manual-view"/);
  assert.match(html, /id="fixture-preset"/);
  assert.match(html, /id="run-fixture"/);
  assert.match(html, /id="reset-fixture"/);
  assert.match(html, /id="visual-qa-script"/);
  assert.match(html, /id="run-visual-qa-script"/);
  assert.match(html, /id="visual-qa-status"/);
  assert.match(html, /id="manual-ready"/);
  assert.match(html, /id="manual-bid"/);
  assert.match(html, /id="manual-trick"/);
  assert.match(html, /id="manual-status"/);
  assert.match(html, /id="hand-status"/);
  assert.match(html, /id="playable-status"/);
  assert.match(html, /id="trick-status"/);
  assert.match(html, /id="hand-summary"/);
  assert.match(html, /id="match-history"/);
  assert.match(html, /id="local-player-stats"/);
  assert.match(html, /id="leaderboard-preview"/);
  assert.match(html, /id="account-match-results"/);
  assert.match(html, /id="reset-local-stats"/);
  assert.match(html, /id="record-tournament-snapshot"/);
  assert.match(html, /id="reset-tournament-history"/);
  assert.match(html, /id="tournament-summary"/);
  assert.match(html, /id="tournament-placements"/);
  assert.match(html, /id="tournament-history"/);
  assert.match(html, /id="play-card-id"/);
  assert.match(html, /id="submit-play-card"/);
  assert.match(html, /id="play-full-hand"/);
  assert.match(html, /id="start-next-hand"/);
  assert.match(html, /id="record-match-history"/);
  assert.match(html, /id="start-new-match"/);
  assert.match(html, /id="manual-full-hand"/);
  assert.match(html, /id="manual-next-hand"/);
  assert.match(html, /id="manual-visual-room"/);
  assert.match(html, /id="manual-visual-phase"/);
  assert.match(html, /id="manual-visual-seat"/);
  assert.match(html, /id="manual-visual-action"/);
  assert.match(html, /id="manual-visual-turn"/);
  assert.match(html, /id="manual-visual-bid"/);
  assert.match(html, /id="manual-visual-playable"/);
  assert.match(html, /id="manual-visual-score-summary"/);
  assert.match(html, /id="manual-visual-bid-bag-summary"/);
  assert.match(html, /id="manual-visual-hand"/);
  assert.match(html, /id="manual-visual-current-trick"/);
  assert.match(html, /id="manual-visual-last-trick"/);
  assert.match(html, /id="manual-qa-check-list"/);
  assert.match(html, /id="manual-qa-edge-list"/);
  assert.match(html, /id="two-seat-visual-compare"/);
  assert.match(html, /id="ready-player"/);
  assert.match(html, /id="leave-room"/);
  assert.doesNotMatch(html, /card-table/i);
});

test("home client wires the shell through the local app controller", () => {
  const client = readFileSync(resolve(appDir, "src/home-client.js"), "utf8");

  assert.match(client, /createSpadesAppController/);
  assert.match(client, /createLocalActionLog/);
  assert.match(client, /createSpadesLiveSyncClient/);
  assert.match(client, /createMockSpadesSocketTransport/);
  assert.match(client, /createSpadesServerClient/);
  assert.match(client, /buildVisualShellModel/);
  assert.match(client, /buildVisualQaReport/);
  assert.match(client, /buildBetaSafetyChecklist/);
  assert.match(client, /friendlyTesterError/);
  assert.match(client, /listManualBetaFlows/);
  assert.match(client, /renderTableLayout/);
  assert.match(client, /renderQaReport/);
  assert.match(client, /renderBetaSafetyPanel/);
  assert.match(client, /renderManualBetaFlows/);
  assert.match(client, /qaReportItem/);
  assert.match(client, /lastSuccessfulAction/);
  assert.match(client, /activeFixturePreset/);
  assert.match(client, /transportMode/);
  assert.match(client, /transportModeSelect/);
  assert.match(client, /reconnectLiveSyncSnapshot/);
  assert.match(client, /activeShellActions/);
  assert.match(client, /isLiveSyncMode/);
  assert.match(client, /isRealServerMode/);
  assert.match(client, /liveSyncActions/);
  assert.match(client, /realServerActions/);
  assert.match(client, /serverStatusFromResponse/);
  assert.match(client, /joinQuickMatch/);
  assert.match(client, /leaveQuickMatch/);
  assert.match(client, /renderQuickMatchStatus/);
  assert.match(client, /createLocalAccountStatsStore/);
  assert.match(client, /createLocalTournamentHistoryStore/);
  assert.match(client, /recordLocalCompletedMatch/);
  assert.match(client, /recordLocalTournamentSnapshot/);
  assert.match(client, /renderAccountsLitePanel/);
  assert.match(client, /renderTournamentHistoryPanel/);
  assert.match(client, /accountStats\.getLeaderboard/);
  assert.match(client, /tournamentHistory\.recordTournament/);
  assert.match(client, /accountStats\.reset/);
  assert.match(client, /tournamentHistory\.reset/);
  assert.match(client, /createLocalPlayerIdentityStore/);
  assert.match(client, /saveCurrentDisplayName/);
  assert.match(client, /rememberSessionFromStatus/);
  assert.match(client, /reconnectStatusFor/);
  assert.match(client, /localPlayerId/);
  assert.match(client, /displayName/);
  assert.match(client, /seatBinding/);
  assert.match(client, /directActions/);
  assert.match(client, /actionLog\.record/);
  assert.match(client, /renderActionLog/);
  assert.match(client, /formatActionLogEntry/);
  assert.match(client, /table-start-new-match/);
  assert.match(client, /runVisualQaScript/);
  assert.match(client, /listVisualQaScripts/);
  assert.match(client, /listManualFixturePresets/);
  assert.match(client, /controller\.createRoom/);
  assert.match(client, /controller\.joinRoom/);
  assert.match(client, /controller\.restoreActiveRoom/);
  assert.match(client, /controller\.readyPlayer/);
  assert.match(client, /controller\.leaveRoom/);
  assert.match(client, /controller\.submitBid/);
  assert.match(client, /controller\.submitPlayCardById/);
  assert.match(client, /visualCardButton/);
  assert.match(client, /aria-label/);
  assert.match(client, /dataset\.cardId/);
  assert.match(client, /card-rank/);
  assert.match(client, /card-suit/);
  assert.match(client, /card-state/);
  assert.match(client, /replaceChildren/);
  assert.match(client, /controller\.playFullHand/);
  assert.match(client, /controller\.startNextHand/);
  assert.match(client, /controller\.recordMatchHistory/);
  assert.match(client, /controller\.getMatchHistory/);
  assert.match(client, /controller\.startNewMatch/);
  assert.match(client, /createTwoSeatManualHarness/);
  assert.match(client, /manualViewSelect/);
  assert.match(client, /manualVisualHandOutput/);
  assert.match(client, /renderVisualShellInto/);
  assert.match(client, /renderTwoSeatVisualCompare/);
  assert.match(client, /manualCardActionForView/);
  assert.match(client, /fixturePresetSelect/);
  assert.match(client, /runPreset/);
  assert.match(client, /formatVisualQaResult/);
  assert.match(client, /showError/);
  assert.match(client, /clearError/);
  assert.match(client, /biddingStatus/);
  assert.doesNotMatch(client, /card-table/i);
});

test("card button styling keeps mobile tap and accessibility states visible", () => {
  const css = readFileSync(resolve(appDir, "src/styles.css"), "utf8");

  assert.match(css, /\.card-button/);
  assert.match(css, /min-height:\s*112px/);
  assert.match(css, /\.card-button\.playable/);
  assert.match(css, /\.card-button:disabled/);
  assert.match(css, /\.card-button:focus-visible/);
  assert.match(css, /\.card-rank/);
  assert.match(css, /\.card-suit/);
  assert.match(css, /\.card-id/);
  assert.match(css, /\.card-state/);
});

test("visual QA and table layout styling is present", () => {
  const css = readFileSync(resolve(appDir, "src/styles.css"), "utf8");

  assert.match(css, /\.table-layout-shell/);
  assert.match(css, /\.table-area/);
  assert.match(css, /\.table-controls/);
  assert.match(css, /\.table-hand-grid/);
  assert.match(css, /\.center-trick-area/);
  assert.match(css, /\.player-hand-area/);
  assert.match(css, /\.qa-report-panel/);
  assert.match(css, /\.beta-safety-panel/);
  assert.match(css, /\.qa-check\.pass/);
  assert.match(css, /\.qa-check\.fail/);
  assert.match(css, /\.action-log-panel/);
  assert.match(css, /\.action-log-entry/);
  assert.match(css, /\.action-log-entry\.fail/);
  assert.match(css, /\.accounts-lite-panel/);
  assert.match(css, /\.tournament-history-panel/);
  assert.match(css, /\.account-stat-grid/);
  assert.match(css, /\.account-stat-item/);
});
