import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const testDir = dirname(fileURLToPath(import.meta.url));
const appDir = resolve(testDir, "..");
const repoDir = resolve(appDir, "../..");

test("basic shell exposes create join ready leave and status targets", () => {
  const html = readFileSync(resolve(appDir, "index.html"), "utf8");

  assert.match(html, /id="jump-to-bug-report"/);
  assert.match(html, /Report Bug/);
  assert.match(html, /id="create-room"/);
  assert.match(html, /id="tester-entry-panel"/);
  assert.match(html, /id="beta-build-label"/);
  assert.match(html, /Spades Hosted Beta v0\.1\.0 Launch Candidate \/ Phase 39/);
  assert.match(html, /Welcome, Beta Tester/);
  assert.match(html, /id="beta-how-to-test"/);
  assert.match(html, /id="beta-quick-checklist"/);
  assert.match(html, /id="final-smoke-test-checklist"/);
  assert.match(html, /Final smoke-test checklist/);
  assert.match(html, /Health check passes/);
  assert.match(html, /Bug report diagnostics copy/);
  assert.match(html, /id="known-issues"/);
  assert.match(html, /Known issues/);
  assert.match(html, /AFK timing is a placeholder/);
  assert.match(html, /id="tester-entry-steps"/);
  assert.match(html, /id="tester-safety-copy"/);
  assert.match(html, /Free play only/);
  assert.match(html, /Create room/);
  assert.match(html, /Join room/);
  assert.match(html, /Quick Match/);
  assert.match(html, /Bid/);
  assert.match(html, /Play hand/);
  assert.match(html, /Reconnect/);
  assert.match(html, /Report bug/);
  assert.match(html, /No cash prizes, no gambling, no payments, and no tournament payouts/);
  assert.match(html, /local previews only/);
  assert.match(html, /Public UI does not show hidden hands, private seat credentials, or host-only data/);
  assert.doesNotMatch(html, /seatToken|admin data|admin-only data|secret/i);
  assert.match(html, /id="transport-mode"/);
  assert.match(html, /id="transport-mode-status"/);
  assert.match(html, /id="connection-help-panel"/);
  assert.match(html, /id="connection-status"/);
  assert.match(html, /id="reconnect-help"/);
  assert.match(html, /id="afk-disconnect-warning"/);
  assert.match(html, /Restore Active Room/);
  assert.match(html, /AFK\/disconnect warning/);
  assert.match(html, /value="real-server"/);
  assert.match(html, /id="join-code"/);
  assert.match(html, /id="join-room"/);
  assert.match(html, /id="restore-room"/);
  assert.match(html, /id="reconnect-live-sync"/);
  assert.match(html, /id="copy-room-code"/);
  assert.match(html, /id="room-code-share-status"/);
  assert.match(html, /Copy Room Code/);
  assert.match(html, /id="join-quick-match"/);
  assert.match(html, /id="leave-quick-match"/);
  assert.match(html, /id="quick-match-status"/);
  assert.match(html, /id="clear-room"/);
  assert.match(html, /Back to Lobby \/ Clear Active Room/);
  assert.match(html, /id="room-status"/);
  assert.match(html, /id="phase-status"/);
  assert.match(html, /id="seat-status"/);
  assert.match(html, /id="turn-status"/);
  assert.match(html, /id="action-status"/);
  assert.match(html, /id="visual-phase"/);
  assert.match(html, /id="visual-seat"/);
  assert.match(html, /id="visual-action"/);
  assert.match(html, /id="visual-score-summary"/);
  assert.match(html, /id="visual-bid-bag-summary"/);
  assert.match(html, /id="visual-hand"/);
  assert.match(html, /id="visual-current-trick"/);
  assert.match(html, /id="visual-last-trick"/);
  assert.match(html, /id="table-opponent-area"/);
  assert.match(html, /id="table-score-area"/);
  assert.match(html, /id="table-center-trick-area"/);
  assert.match(html, /id="table-last-trick-area"/);
  assert.match(html, /id="table-player-hand-area"/);
  assert.match(html, /id="table-leave-room"/);
  assert.match(html, /Leave Room \/ Back to Lobby/);
  assert.match(html, /id="table-record-history"/);
  assert.match(html, /id="table-start-next-hand"/);
  assert.match(html, /id="table-start-new-match"/);
  assert.match(html, /id="qa-check-list"/);
  assert.match(html, /id="qa-edge-list"/);
  assert.match(html, /id="beta-safety-check-list"/);
  assert.match(html, /id="manual-beta-flow-list"/);
  assert.match(html, /id="beta-feedback-title"/);
  assert.match(html, /id="beta-issue-title"/);
  assert.match(html, /id="beta-issue-steps"/);
  assert.match(html, /id="beta-issue-expected"/);
  assert.match(html, /id="beta-issue-actual"/);
  assert.match(html, /id="beta-diagnostics-bundle"/);
  assert.match(html, /id="refresh-diagnostics"/);
  assert.match(html, /id="copy-diagnostics"/);
  assert.match(html, /id="save-beta-report"/);
  assert.match(html, /id="export-beta-reports"/);
  assert.match(html, /id="clear-beta-reports"/);
  assert.match(html, /id="beta-feedback-status"/);
  assert.match(html, /id="beta-report-history"/);
  assert.match(html, /Send this to dev/);
  assert.match(html, /id="advanced-diagnostics"/);
  assert.match(html, /Advanced diagnostics/);
  assert.match(html, /Sanitized QA Report/);
  assert.match(html, /id="action-log-list"/);
  assert.match(html, /id="bid-status"/);
  assert.match(html, /id="bid-input"/);
  assert.match(html, /id="submit-bid"/);
  assert.match(html, /id="submit-nil"/);
  assert.match(html, /id="shell-error"/);
  assert.match(html, /id="manual-setup"/);
  assert.match(html, /id="manual-view"/);
  assert.match(html, /id="fixture-preset"/);
  assert.match(html, /id="run-fixture"/);
  assert.match(html, /id="reset-fixture"/);
  assert.match(html, /id="visual-qa-script"/);
  assert.match(html, /id="run-visual-qa-script"/);
  assert.match(html, /id="visual-qa-status"/);
  assert.match(html, /id="manual-ready"/);
  assert.match(html, /id="manual-bid"/);
  assert.match(html, /id="manual-trick"/);
  assert.match(html, /id="manual-status"/);
  assert.match(html, /id="hand-status"/);
  assert.match(html, /id="playable-status"/);
  assert.match(html, /id="trick-status"/);
  assert.match(html, /id="hand-summary"/);
  assert.match(html, /id="match-history"/);
  assert.match(html, /id="local-preview-tools"/);
  assert.match(html, /Local preview tools/);
  assert.match(html, /Local Stats Preview/);
  assert.match(html, /id="local-player-stats"/);
  assert.match(html, /id="leaderboard-preview"/);
  assert.match(html, /id="account-match-results"/);
  assert.match(html, /id="reset-local-stats"/);
  assert.match(html, /id="record-tournament-snapshot"/);
  assert.match(html, /Record Local History Snapshot/);
  assert.match(html, /id="reset-tournament-history"/);
  assert.match(html, /Reset Local History/);
  assert.match(html, /id="tournament-summary"/);
  assert.match(html, /id="tournament-placements"/);
  assert.match(html, /id="tournament-history"/);
  assert.match(html, /id="play-card-id"/);
  assert.match(html, /id="submit-play-card"/);
  assert.match(html, /id="play-full-hand"/);
  assert.match(html, /id="start-next-hand"/);
  assert.match(html, /id="record-match-history"/);
  assert.match(html, /id="start-new-match"/);
  assert.match(html, /id="manual-test-tools"/);
  assert.match(html, /Manual local test tools/);
  assert.match(html, /id="manual-full-hand"/);
  assert.match(html, /id="manual-next-hand"/);
  assert.match(html, /id="manual-visual-room"/);
  assert.match(html, /id="manual-visual-phase"/);
  assert.match(html, /id="manual-visual-seat"/);
  assert.match(html, /id="manual-visual-action"/);
  assert.match(html, /id="manual-visual-turn"/);
  assert.match(html, /id="manual-visual-bid"/);
  assert.match(html, /id="manual-visual-playable"/);
  assert.match(html, /id="manual-visual-score-summary"/);
  assert.match(html, /id="manual-visual-bid-bag-summary"/);
  assert.match(html, /id="manual-visual-hand"/);
  assert.match(html, /id="manual-visual-current-trick"/);
  assert.match(html, /id="manual-visual-last-trick"/);
  assert.match(html, /id="manual-qa-check-list"/);
  assert.match(html, /id="manual-qa-edge-list"/);
  assert.match(html, /id="two-seat-visual-compare"/);
  assert.match(html, /id="ready-player"/);
  assert.match(html, /id="leave-room"/);
  assert.match(html, /id="leave-room-help"/);
  assert.doesNotMatch(html, /card-table/i);
});

test("home client wires the shell through the local app controller", () => {
  const client = readFileSync(resolve(appDir, "src/home-client.js"), "utf8");

  assert.match(client, /createSpadesAppController/);
  assert.match(client, /createLocalActionLog/);
  assert.match(client, /createSpadesLiveSyncClient/);
  assert.match(client, /createMockSpadesSocketTransport/);
  assert.match(client, /createSpadesServerClient/);
  assert.match(client, /buildVisualShellModel/);
  assert.match(client, /buildVisualQaReport/);
  assert.match(client, /buildBetaSafetyChecklist/);
  assert.match(client, /buildDiagnosticsBundle/);
  assert.match(client, /createBetaIssueReport/);
  assert.match(client, /createLocalBetaFeedbackStore/);
  assert.match(client, /formatDiagnosticsSummary/);
  assert.match(client, /currentDiagnosticsBundle/);
  assert.match(client, /renderBetaFeedbackPanel/);
  assert.match(client, /copyDiagnosticsBundle/);
  assert.match(client, /copyRoomCode/);
  assert.match(client, /renderConnectionHelp/);
  assert.match(client, /connectionStatusLabel/);
  assert.match(client, /renderRoomCodeShare/);
  assert.match(client, /scrollIntoView/);
  assert.match(client, /hiddenHandSafe/);
  assert.match(client, /friendlyTesterError/);
  assert.match(client, /listManualBetaFlows/);
  assert.match(client, /renderTableLayout/);
  assert.match(client, /renderQaReport/);
  assert.match(client, /renderBetaSafetyPanel/);
  assert.match(client, /renderManualBetaFlows/);
  assert.match(client, /qaReportItem/);
  assert.match(client, /lastSuccessfulAction/);
  assert.match(client, /activeFixturePreset/);
  assert.match(client, /transportMode/);
  assert.match(client, /transportModeSelect/);
  assert.match(client, /reconnectLiveSyncSnapshot/);
  assert.match(client, /activeShellActions/);
  assert.match(client, /isLiveSyncMode/);
  assert.match(client, /isRealServerMode/);
  assert.match(client, /liveSyncActions/);
  assert.match(client, /realServerActions/);
  assert.match(client, /serverStatusFromResponse/);
  assert.match(client, /joinQuickMatch/);
  assert.match(client, /leaveQuickMatch/);
  assert.match(client, /renderQuickMatchStatus/);
  assert.match(client, /createLocalAccountStatsStore/);
  assert.match(client, /createLocalTournamentHistoryStore/);
  assert.match(client, /recordLocalCompletedMatch/);
  assert.match(client, /recordLocalTournamentSnapshot/);
  assert.match(client, /renderAccountsLitePanel/);
  assert.match(client, /renderTournamentHistoryPanel/);
  assert.match(client, /accountStats\.getLeaderboard/);
  assert.match(client, /tournamentHistory\.recordTournament/);
  assert.match(client, /accountStats\.reset/);
  assert.match(client, /tournamentHistory\.reset/);
  assert.match(client, /createLocalPlayerIdentityStore/);
  assert.match(client, /saveCurrentDisplayName/);
  assert.match(client, /rememberSessionFromStatus/);
  assert.match(client, /reconnectStatusFor/);
  assert.match(client, /localPlayerId/);
  assert.match(client, /displayName/);
  assert.match(client, /seatBinding/);
  assert.match(client, /directActions/);
  assert.match(client, /actionLog\.record/);
  assert.match(client, /renderActionLog/);
  assert.match(client, /formatActionLogEntry/);
  assert.match(client, /table-start-new-match/);
  assert.match(client, /runVisualQaScript/);
  assert.match(client, /listVisualQaScripts/);
  assert.match(client, /listManualFixturePresets/);
  assert.match(client, /controller\.createRoom/);
  assert.match(client, /controller\.joinRoom/);
  assert.match(client, /controller\.restoreActiveRoom/);
  assert.match(client, /controller\.readyPlayer/);
  assert.match(client, /controller\.leaveRoom/);
  assert.match(client, /controller\.submitBid/);
  assert.match(client, /controller\.submitPlayCardById/);
  assert.match(client, /visualCardButton/);
  assert.match(client, /aria-label/);
  assert.match(client, /dataset\.cardId/);
  assert.match(client, /card-rank/);
  assert.match(client, /card-suit/);
  assert.match(client, /card-state/);
  assert.match(client, /replaceChildren/);
  assert.match(client, /controller\.playFullHand/);
  assert.match(client, /controller\.startNextHand/);
  assert.match(client, /controller\.recordMatchHistory/);
  assert.match(client, /controller\.getMatchHistory/);
  assert.match(client, /controller\.startNewMatch/);
  assert.match(client, /createTwoSeatManualHarness/);
  assert.match(client, /manualViewSelect/);
  assert.match(client, /manualVisualHandOutput/);
  assert.match(client, /renderVisualShellInto/);
  assert.match(client, /renderTwoSeatVisualCompare/);
  assert.match(client, /manualCardActionForView/);
  assert.match(client, /fixturePresetSelect/);
  assert.match(client, /runPreset/);
  assert.match(client, /formatVisualQaResult/);
  assert.match(client, /showError/);
  assert.match(client, /clearError/);
  assert.match(client, /biddingStatus/);
  assert.doesNotMatch(client, /card-table/i);
});

test("card button styling keeps mobile tap and accessibility states visible", () => {
  const css = readFileSync(resolve(appDir, "src/styles.css"), "utf8");

  assert.match(css, /\.card-button/);
  assert.match(css, /min-height:\s*112px/);
  assert.match(css, /\.card-button\.playable/);
  assert.match(css, /\.card-button:disabled/);
  assert.match(css, /\.card-button:focus-visible/);
  assert.match(css, /\.card-rank/);
  assert.match(css, /\.card-suit/);
  assert.match(css, /\.card-id/);
  assert.match(css, /\.card-state/);
});

test("visual QA and table layout styling is present", () => {
  const css = readFileSync(resolve(appDir, "src/styles.css"), "utf8");

  assert.match(css, /\.tester-entry-panel/);
  assert.match(css, /\.bug-report-fab/);
  assert.match(css, /position:\s*fixed/);
  assert.match(css, /\.beta-build-label/);
  assert.match(css, /\.beta-onboarding-block/);
  assert.match(css, /\.connection-help-panel/);
  assert.match(css, /\.developer-details/);
  assert.match(css, /\.developer-details > summary/);
  assert.match(css, /padding-bottom:\s*80px/);
  assert.match(css, /\.tester-entry-note/);
  assert.match(css, /\.table-layout-shell/);
  assert.match(css, /\.table-area/);
  assert.match(css, /\.table-controls/);
  assert.match(css, /\.table-hand-grid/);
  assert.match(css, /\.center-trick-area/);
  assert.match(css, /\.player-hand-area/);
  assert.match(css, /\.qa-report-panel/);
  assert.match(css, /\.beta-safety-panel/);
  assert.match(css, /\.beta-feedback-panel/);
  assert.match(css, /\.feedback-form-grid/);
  assert.match(css, /\.qa-check\.pass/);
  assert.match(css, /\.qa-check\.fail/);
  assert.match(css, /\.action-log-panel/);
  assert.match(css, /\.action-log-entry/);
  assert.match(css, /\.action-log-entry\.fail/);
  assert.match(css, /\.accounts-lite-panel/);
  assert.match(css, /\.tournament-history-panel/);
  assert.match(css, /\.account-stat-grid/);
  assert.match(css, /\.account-stat-item/);
});

test("hosted deploy checklist and server startup are present", () => {
  const packageJson = readFileSync(resolve(appDir, "package.json"), "utf8");
  const server = readFileSync(resolve(appDir, "server.js"), "utf8");
  const checklist = readFileSync(resolve(appDir, "DEPLOY_CHECKLIST.md"), "utf8");
  const smokeScript = readFileSync(resolve(appDir, "scripts/hosted-beta-smoke.mjs"), "utf8");
  const testerGuide = readFileSync(resolve(repoDir, "docs/BETA_TESTER_GUIDE.md"), "utf8");
  const externalChecklist = readFileSync(resolve(repoDir, "docs/EXTERNAL_TESTER_CHECKLIST.md"), "utf8");
  const finalSmokeChecklist = readFileSync(resolve(repoDir, "docs/FINAL_SMOKE_TEST_CHECKLIST.md"), "utf8");
  const launchDoc = readFileSync(resolve(repoDir, "docs/SPADES_HOSTED_BETA_LAUNCH.md"), "utf8");
  const feedbackDoc = readFileSync(resolve(repoDir, "docs/SPADES_BETA_FEEDBACK.md"), "utf8");
  const productionConfig = readFileSync(resolve(repoDir, "docs/PRODUCTION_CONFIG_CHECKLIST.md"), "utf8");
  const testerInvite = readFileSync(resolve(repoDir, "docs/BETA_TESTER_INVITE.md"), "utf8");
  const releaseNotes = readFileSync(resolve(repoDir, "docs/SPADES_BETA_RELEASE_NOTES.md"), "utf8");

  assert.match(packageJson, /"start": "node server\.js"/);
  assert.match(packageJson, /"smoke:hosted": "node scripts\/hosted-beta-smoke\.mjs"/);
  assert.match(server, /resolveServerEnvConfig/);
  assert.match(server, /createSpadesHostedServer/);
  assert.match(server, /logger\.info/);
  assert.match(server, /SIGTERM/);
  assert.match(server, /SIGINT/);
  assert.doesNotMatch(server, /hand|seatToken|secret/i);
  assert.match(smokeScript, /runHostedBetaSmokeTest/);
  assert.match(smokeScript, /SPADES_PUBLIC_API_URL/);
  assert.match(smokeScript, /SPADES_PUBLIC_WS_URL/);
  assert.match(smokeScript, /validateSmokeConfig/);
  assert.match(smokeScript, /API URL must use http or https/);
  assert.match(smokeScript, /WebSocket URL must use ws or wss/);
  assert.match(smokeScript, /Hosted HTTPS API requires WSS/);
  assert.match(checklist, /SPADES_PUBLIC_API_URL/);
  assert.match(checklist, /SPADES_PUBLIC_WS_URL/);
  assert.match(checklist, /PUBLIC_API_URL/);
  assert.match(checklist, /PUBLIC_WS_URL/);
  assert.match(checklist, /SPADES_BIND_HOST/);
  assert.match(checklist, /npm run smoke:hosted/);
  assert.match(checklist, /one full trick/);
  assert.match(checklist, /Complete a hand/);
  assert.match(checklist, /free play/i);
  assert.match(checklist, /no.*gambling/i);
  assert.match(checklist, /Production Config Checklist/);
  assert.match(checklist, /Backend URL \/ WebSocket URL Validation/);
  assert.match(checklist, /API URL must use `http:\/\/` or `https:\/\/`/);
  assert.match(checklist, /Hosted `https:\/\/` API requires a `wss:\/\/` WebSocket URL/);
  assert.match(checklist, /API And UI Safety Confirmations/);
  assert.match(checklist, /private seat tokens/);
  assert.match(checklist, /admin keys/);
  assert.match(checklist, /SPADES_BETA_RELEASE_NOTES\.md/);
  assert.match(checklist, /BETA_TESTER_INVITE\.md/);
  assert.match(checklist, /Tester Entry Steps/);
  assert.match(checklist, /visible beta build label/);
  assert.match(checklist, /Create a room/);
  assert.match(checklist, /Join a room by code/);
  assert.match(checklist, /Quick Match/);
  assert.match(checklist, /Ready both players, bid, and play at least one hand/);
  assert.match(checklist, /Restore Active Room/);
  assert.match(checklist, /Beta Feedback Report/);
  assert.match(checklist, /no cash prizes, no gambling, no payments, and no tournament payouts/i);
  assert.match(checklist, /External Tester Hardening Checks/);
  assert.match(checklist, /connection status panel/);
  assert.match(checklist, /AFK\/disconnect warning placeholder/);
  assert.match(checklist, /Copy Room Code/);
  assert.match(checklist, /Report Bug button/);
  assert.match(checklist, /failed join, room full, stale action, and disconnected/i);
  assert.match(checklist, /Launch Candidate Final Smoke Test/);
  assert.match(checklist, /launch candidate/);
  assert.match(checklist, /all public text is free play only/i);
  assert.match(checklist, /advanced diagnostics and local preview tools are collapsed by default/i);
  assert.match(checklist, /copyable diagnostics section remains visible/i);
  assert.match(checklist, /Known Issues For Testers/);
  assert.match(checklist, /mobile layout has no horizontal scrolling/i);
  assert.match(checklist, /FINAL_SMOKE_TEST_CHECKLIST\.md/);
  assert.match(checklist, /Render/);
  assert.match(checklist, /Railway/);
  assert.match(checklist, /Fly/);
  assert.match(checklist, /Hosted Smoke Test/);
  assert.match(checklist, /Rollback Notes/);
  assert.match(launchDoc, /free play only/i);
  assert.match(launchDoc, /Create a room and share the code/);
  assert.match(launchDoc, /Join a room by code/);
  assert.match(launchDoc, /Quick Match/);
  assert.match(launchDoc, /Play one full trick/);
  assert.match(launchDoc, /Complete one hand/);
  assert.match(launchDoc, /no wagers, prizes, payments, gambling features, or tournament payouts/i);
  assert.match(testerGuide, /Spades Hosted Beta Tester Guide/);
  assert.match(testerGuide, /free play only/i);
  assert.match(testerGuide, /no cash prizes/i);
  assert.match(testerGuide, /no gambling/i);
  assert.match(testerGuide, /Quick Checklist/);
  assert.match(testerGuide, /Create room/);
  assert.match(testerGuide, /Join room/);
  assert.match(testerGuide, /Quick Match/);
  assert.match(testerGuide, /Bid/);
  assert.match(testerGuide, /Play hand/);
  assert.match(testerGuide, /Reconnect/);
  assert.match(testerGuide, /Report bug/);
  assert.match(testerGuide, /Copy Diagnostics/);
  assert.match(externalChecklist, /Spades External Tester Checklist/);
  assert.match(externalChecklist, /free play only/i);
  assert.match(externalChecklist, /no cash prizes/i);
  assert.match(externalChecklist, /no gambling/i);
  assert.match(externalChecklist, /connection status panel/i);
  assert.match(externalChecklist, /Copy Room Code|Copy\/share the room code/i);
  assert.match(externalChecklist, /AFK\/disconnect warning placeholder/);
  assert.match(externalChecklist, /Leave Room \/ Back to Lobby/);
  assert.match(externalChecklist, /always-visible Report Bug button/);
  assert.match(externalChecklist, /failed join/i);
  assert.match(externalChecklist, /room full/i);
  assert.match(externalChecklist, /stale action/i);
  assert.match(externalChecklist, /disconnected/i);
  assert.match(finalSmokeChecklist, /Spades Launch Candidate Final Smoke-Test Checklist/);
  assert.match(finalSmokeChecklist, /free play only/i);
  assert.match(finalSmokeChecklist, /Public Text Check/);
  assert.match(finalSmokeChecklist, /Production Config Check/);
  assert.match(finalSmokeChecklist, /SPADES_PUBLIC_API_URL/);
  assert.match(finalSmokeChecklist, /SPADES_PUBLIC_WS_URL/);
  assert.match(finalSmokeChecklist, /Hosted API URL uses `https:\/\/`/);
  assert.match(finalSmokeChecklist, /Hosted WebSocket URL uses `wss:\/\/`/);
  assert.match(finalSmokeChecklist, /Mobile Layout Check/);
  assert.match(finalSmokeChecklist, /Multiplayer Smoke Path/);
  assert.match(finalSmokeChecklist, /Data Safety Check/);
  assert.match(finalSmokeChecklist, /API responses do not include hidden opponent hands/);
  assert.match(finalSmokeChecklist, /Health responses do not include hidden hands, tokens, or admin keys/);
  assert.match(finalSmokeChecklist, /Rollback Check/);
  assert.match(finalSmokeChecklist, /Known Issues/);
  assert.match(finalSmokeChecklist, /Advanced diagnostics and local test tools are collapsed by default/);
  assert.match(finalSmokeChecklist, /Copyable diagnostics do not include hidden hands, private seat credentials, host-only data, or secrets/);
  assert.match(feedbackDoc, /copyable diagnostics bundle/i);
  assert.match(feedbackDoc, /room code/i);
  assert.match(feedbackDoc, /phase/i);
  assert.match(feedbackDoc, /transport/i);
  assert.match(feedbackDoc, /seat/i);
  assert.match(feedbackDoc, /last action/i);
  assert.match(feedbackDoc, /last error/i);
  assert.match(feedbackDoc, /hidden-hand safety/i);
  assert.match(productionConfig, /Spades Hosted Beta Production Config Checklist/);
  assert.match(productionConfig, /free-play hosted beta only/i);
  assert.match(productionConfig, /SPADES_PUBLIC_API_URL/);
  assert.match(productionConfig, /SPADES_PUBLIC_WS_URL/);
  assert.match(productionConfig, /PUBLIC_API_URL/);
  assert.match(productionConfig, /PUBLIC_WS_URL/);
  assert.match(productionConfig, /Hosted API URLs must be absolute `https:\/\/` URLs/);
  assert.match(productionConfig, /Hosted WebSocket URLs must be absolute `wss:\/\/` URLs ending in `\/ws`/);
  assert.match(productionConfig, /hidden hands/);
  assert.match(productionConfig, /private seat tokens/);
  assert.match(productionConfig, /admin keys/);
  assert.match(productionConfig, /Rollback Instructions/);
  assert.match(testerInvite, /Spades Hosted Beta Tester Invite Copy/);
  assert.match(testerInvite, /free-play Spades beta/i);
  assert.match(testerInvite, /Create a room/);
  assert.match(testerInvite, /Join a room by code/);
  assert.match(testerInvite, /Quick Match/);
  assert.match(testerInvite, /bid, and play at least one hand/i);
  assert.match(testerInvite, /Restore Active Room/);
  assert.match(testerInvite, /Report Bug/);
  assert.match(testerInvite, /diagnostics bundle/);
  assert.match(testerInvite, /no cash prizes, no gambling, no payments, and no tournament payouts/i);
  assert.match(releaseNotes, /Spades Hosted Beta Release Notes/);
  assert.match(releaseNotes, /Phase 39/);
  assert.match(releaseNotes, /free play only/i);
  assert.match(releaseNotes, /no cash prizes, no gambling, no payments, and no tournament payouts/i);
  assert.match(releaseNotes, /HTTP and WebSocket local server boundary/);
  assert.match(releaseNotes, /hidden hands/);
  assert.match(releaseNotes, /private seat tokens/);
  assert.match(releaseNotes, /admin keys/);
  assert.match(releaseNotes, /Known Issues/);
  assert.match(releaseNotes, /Rollback/);
});
